spring:
  profiles: real
  
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:sqlite:{DB filepath}
    username: 
    password: 

multipart:
  maxFileSize: 10MB
  maxRequestSize: 10MB

mybatis:
  config-location: classpath:/mybatis/config/mybatis-config.xml
  
server:
  port: 8080
  contextPath: /
  tomcat:
    uri-encoding: UTF-8
  
security:
  basic:
    enabled: false
        
management:
  port: 8091
  security:
    enabled: false
    
logging:
  config: classpath:logback-real.xml
  
courage:
  web:
    title: COURAGE-PORTFOLIO
  storage:
    savePath: {attachments filepath}
    whiteList: jpg, jpeg, png, gif
  resource:
    jsExt: min.js
    cssExt: min.js