spring:
  profiles: default
  
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:sqlite:C:/dev/courage-portfolio.db
    username: 
    password: 

mybatis:
  config-location: classpath:/mybatis/config/mybatis-config.xml
  
server:
  port: 8080
  contextPath: /
  tomcat:
    uri-encoding: UTF-8
  session:
    timeout: 3600
  
security:
  basic:
    enabled: false
    
management:
  port: 8091
  security:
    enabled: false
    
logging:
  config: classpath:logback-default.xml
  
courage:
  web:
    title: Courage PortfoLog
  storage:
    savePath: C:/dev/kaki/attachments
    whiteList: jpg, jpeg, png, gif
  resource:
    jsExt: js
    cssExt: css
  session:
    keys:
      object: loginInfo
      name: name
      email: email
      gravatarURL: gravatarURL
  link:
    gravatar:
      url: https://www.gravatar.com/avatar/
      defaultImg: identicon
      size: 50