spring:
  profiles: real
  thymeleaf:
    mode: HTML5
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:sqlite:{DB filepath}
    username: 
    password: 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    
mybatis:
  config-location: classpath:/mybatis/config/mybatis-config.xml
  
server:
  port: 8080
  contextPath: /
  tomcat:
    uri-encoding: UTF-8
  session:
    timeout: 3600
  
security:
  basic:
    enabled: false
        
management:
  port: 8091
  security:
    enabled: false
    
logging:
  config: classpath:logback-real.xml
  
courage:
  web:
    title: COURAGE
  admin:
    title: Admin
  storage:
    savePath: {attachments filepath}
    whiteList: jpg, jpeg, png, gif
  resource:
    jsExt: min.js
    cssExt: min.js
  session:
    keys:
      object: loginInfo
      name: name
      email: email
      gravatarURL: gravatarURL
  link:
    gravatar:
      url: https://www.gravatar.com/avatar/
      defaultImg: /images/avatar/anonymous.png
      size: 50
  board:
    contact:
      page-size: 15