CREATE TABLE `TB_MEMBER` (
	`SNO` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`NAME` TEXT NOT NULL,
	`PASSWORD` TEXT NOT NULL,
	`SALT` TEXT NOT NULL,
	`EMAIL` TEXT NOT NULL );

CREATE TABLE `TB_SETUP` ( 
	`PB_SNO` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	`TITLE` TEXT, 
	`SUB_TITLE` TEXT, 
	`MAIN_PHOTO_URL` TEXT, 
	`ABOUT_ME` TEXT, 
	`LOCATION` TEXT, 
	`AROUND_THE_WEB` TEXT, 
	`GITHUB` TEXT, 
	`FACEBOOK` TEXT, 
	`TWITTER` TEXT, 
	`GOOGLE_PLUS` TEXT, 
	`LINKED_IN` TEXT, 
	`CREATE_BY` TEXT );